feature_extractor: 'MobileNetV3'
device: 0

clip_length_seconds: 30
clip_fps: 5
clip_width: 256

# Video preprocessing params
resize_size: 256
fps: 5

# Faiss
indexer_params:
  nlist: 100
  d: 1280
  M: 16
  nbits: 8
  hnsw_m: 32